---
- name: Display Facts about BGP
  hosts: vsrx
  connection: local
  gather_facts: no

  tasks:
    - name: gathering info from device
      junos_get_facts: 
        user=root
        passwd=Juniper1!
        port={{ ncssh_port }}
        host={{ ip_addr }}
      register: junos

    - name: bgp_info
      debug: msg={{ item }}
      with_dict: junos.facts