---
- name: Debug Info
  hosts: lab
  gather_facts: yes

  tasks:
  - name: Show operating system
    debug: 
      msg="{{ansible_os_family}}"
  - name: Show product
    debug: 
      msg="System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }}"
  - name: Show gateway
    debug: 
      msg="System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
    when: ansible_default_ipv4.gateway is defined

# This module prints statements during execution and can be useful for debugging 
# variables or expressions without necessarily halting the playbook. Useful for 
# debugging together with the ‘when:’ directive. 其中所使用的變量均為Ansible中的環境變量
# 無需手動定義
