---
- name: multiple tasks
  hosts: lab
  gather_facts: fales

  vars:
  - new_user: "enigma"

  tasks:
  - name: create {{ new_user }}
    user:
      name="{{ new_user }}"
      password="qwerasdf"
    sudo: yes
  - name: start service
    service:
      name=nginx
      state=started
    sudo: yes
